// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPRLxMJ-kaFbb3Twn9QxGMIOxyfw8km1Q',
    appId: '1:712562696576:android:bd406c716b149d66fea165',
    messagingSenderId: '712562696576',
    projectId: 'doctor-appointment-d7c59',
    storageBucket: 'doctor-appointment-d7c59.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByDAFzMbweKHKapS2L3xt1qt4nQkoX08Q',
    appId: '1:712562696576:web:dbcccf4743643ef8fea165',
    messagingSenderId: '712562696576',
    projectId: 'doctor-appointment-d7c59',
    authDomain: 'doctor-appointment-d7c59.firebaseapp.com',
    storageBucket: 'doctor-appointment-d7c59.appspot.com',
    measurementId: 'G-3V3VJXKVMK',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByDAFzMbweKHKapS2L3xt1qt4nQkoX08Q',
    appId: '1:712562696576:web:d3ce3f01593d098ffea165',
    messagingSenderId: '712562696576',
    projectId: 'doctor-appointment-d7c59',
    authDomain: 'doctor-appointment-d7c59.firebaseapp.com',
    storageBucket: 'doctor-appointment-d7c59.appspot.com',
    measurementId: 'G-D0L4PS37YF',
  );

}